CREATE DATABASE inventory;
\c inventory;
CREATE TABLE products (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
quantity INTEGER NOT NULL,
price NUMERIC(10,2) NOT NULL,
category VARCHAR(50) NOT NULL
);